import { Component } from '@angular/core';
import {RelativeDTO} from "./intefaces/relativeDTO";
import {TableLazyLoadEvent} from "primeng/table";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'AngularExample';
  hideTable:boolean = true;
  selectedRowData:RelativeDTO | null = null;

  columns = [
    { field: 'relationDegree', header: 'Тип родственной связи' },
    { field: 'fullname', header: 'Имя' },
    { field: 'birthDate', header: 'Дата Рождения' },
    { field: 'workplace', header: 'Лавозим' },
    {field: 'education', header: 'Укув тури'},
    {field: 'address', header: 'Адрес'}

  ];
  staffRelativeList = [
    {
      "id": 1214372,
      "surname": "Дурдиметов",
      "name": "Аллаберди",
      "patronymic": "Палтаевич",
      "fullName": "Дурдиметов Аллаберди Палтаевич",
      "pINFL": "31506773490078",
      "birthDate": "1977-06-15",
      "countryBirthId": "",
      "regionBirthId": "",
      "placeBirth": "Хожели тумани",
      "spRelationDegreeId": "1",
      "spRelationDegreeName": "Otasi",
      "spCitizenshipId": null,
      "spCitizenshipLabel": null,
      "passportSeria": "KA",
      "passportNumber": "0291963",
      "birthCertificateSeria": null,
      "birthCertificateNumber": null,
      "companyName": "СР ШК N 14",
      "workAdress": null,
      "position": "Ўқитувчи",
      "regionResidenceId": "",
      "districtResidenceId": "",
      "placeOfResidence": null,
      "file": null,
      "staffId": 2257,
      "structureName": "Педагоглар",
      "currentpositionId": null,
      "profileId": null,
      "argosId": null,
      "tin": null,
      "regionEducationId": "",
      "districtEducationId": "",
      "educationalInstitution": null,
      "address": "Қорақалпоғистон Республикаси,  Такиятош шаҳри",
      "pensionDateBegin": null,
      "pensionType": null,
      "status": "",
      "dateOfDeath": null,
      "isChild": null,
      "relativeWorkType": 2,
      "citizenType": null,
      "isSameOrganization": 0,
      "underAgeType": null,
      "ordered": 1,
      "relationId": 1,
      "birthOfDate": "1977-06-15T00:00:00",
      "yearOfDeath": 0,
      "districtBirthId": null
    },
    {
      "id": 1214371,
      "surname": "Дурдиметова",
      "name": "Майса",
      "patronymic": "Ниязмурадовна",
      "fullName": "Дурдиметова Майса Ниязмурадовна",
      "pINFL": null,
      "birthDate": "1975-06-25",
      "countryBirthId": "",
      "regionBirthId": "",
      "placeBirth": "Лебап",
      "spRelationDegreeId": "2",
      "spRelationDegreeName": "Onasi",
      "spCitizenshipId": null,
      "spCitizenshipLabel": null,
      "passportSeria": null,
      "passportNumber": null,
      "birthCertificateSeria": null,
      "birthCertificateNumber": null,
      "companyName": null,
      "workAdress": null,
      "position": null,
      "regionResidenceId": "",
      "districtResidenceId": "",
      "placeOfResidence": null,
      "file": null,
      "staffId": 2257,
      "structureName": null,
      "currentpositionId": null,
      "profileId": null,
      "argosId": null,
      "tin": null,
      "regionEducationId": "",
      "districtEducationId": "",
      "educationalInstitution": null,
      "address": "Қорақалпоғистон Республикаси,  Тахиатош тумани",
      "pensionDateBegin": null,
      "pensionType": null,
      "status": "",
      "dateOfDeath": null,
      "isChild": null,
      "relativeWorkType": null,
      "citizenType": null,
      "isSameOrganization": 0,
      "underAgeType": null,
      "ordered": 2,
      "relationId": 2,
      "birthOfDate": "1975-06-25T00:00:00",
      "yearOfDeath": 0,
      "districtBirthId": null
    },
    {
      "id": 1214369,
      "surname": "Палтаева",
      "name": "Женнет",
      "patronymic": "Аллабердиевна",
      "fullName": "Палтаева Женнет Аллабердиевна",
      "pINFL": "41111987380014",
      "birthDate": "1998-11-11",
      "countryBirthId": "",
      "regionBirthId": "",
      "placeBirth": "Хожели тумани",
      "spRelationDegreeId": "4",
      "spRelationDegreeName": "Opasi/Singlisi",
      "spCitizenshipId": null,
      "spCitizenshipLabel": null,
      "passportSeria": "KA",
      "passportNumber": "0465231",
      "birthCertificateSeria": null,
      "birthCertificateNumber": null,
      "companyName": null,
      "workAdress": null,
      "position": null,
      "regionResidenceId": "",
      "districtResidenceId": "",
      "placeOfResidence": null,
      "file": null,
      "staffId": 2257,
      "structureName": null,
      "currentpositionId": null,
      "profileId": null,
      "argosId": null,
      "tin": null,
      "regionEducationId": "",
      "districtEducationId": "",
      "educationalInstitution": null,
      "address": "Қорақалпоғистон Республикаси,  Такиятош шаҳри",
      "pensionDateBegin": null,
      "pensionType": null,
      "status": "",
      "dateOfDeath": null,
      "isChild": null,
      "relativeWorkType": null,
      "citizenType": null,
      "isSameOrganization": 0,
      "underAgeType": null,
      "ordered": 3,
      "relationId": 4,
      "birthOfDate": "1998-11-11T00:00:00",
      "yearOfDeath": 0,
      "districtBirthId": null
    },
    {
      "id": 1214368,
      "surname": "Палтаева",
      "name": "Дилназ",
      "patronymic": "Аллаберди қизи",
      "fullName": "Палтаева Дилназ Аллаберди қизи",
      "pINFL": null,
      "birthDate": "2006-05-29",
      "countryBirthId": "",
      "regionBirthId": "",
      "placeBirth": "Қорақалпоғистон Республикаси",
      "spRelationDegreeId": "4",
      "spRelationDegreeName": "Singlisi",
      "spCitizenshipId": null,
      "spCitizenshipLabel": null,
      "passportSeria": null,
      "passportNumber": null,
      "birthCertificateSeria": null,
      "birthCertificateNumber": null,
      "companyName": null,
      "workAdress": null,
      "position": null,
      "regionResidenceId": "",
      "districtResidenceId": "",
      "placeOfResidence": null,
      "file": null,
      "staffId": 2257,
      "structureName": null,
      "currentpositionId": null,
      "profileId": null,
      "argosId": null,
      "tin": null,
      "regionEducationId": "",
      "districtEducationId": "",
      "educationalInstitution": null,
      "address": "Қорақалпоғистон Республикаси,  Тахиатош тумани",
      "pensionDateBegin": null,
      "pensionType": null,
      "status": "Мактаб/Лицей/Коллеж ўқувчиси",
      "dateOfDeath": null,
      "isChild": null,
      "relativeWorkType": null,
      "citizenType": null,
      "isSameOrganization": 0,
      "underAgeType": null,
      "ordered": 3,
      "relationId": 4,
      "birthOfDate": "2006-05-29T00:00:00",
      "yearOfDeath": 0,
      "districtBirthId": null
    },
    {
      "id": 1214370,
      "surname": "Палтаев",
      "name": "Кияс",
      "patronymic": "Аллабердиевич",
      "fullName": "Палтаев Кияс Аллабердиевич",
      "pINFL": null,
      "birthDate": "2009-01-14",
      "countryBirthId": "",
      "regionBirthId": "",
      "placeBirth": "Қорақалпоғистон Республикаси",
      "spRelationDegreeId": "3",
      "spRelationDegreeName": "Ukasi",
      "spCitizenshipId": null,
      "spCitizenshipLabel": null,
      "passportSeria": null,
      "passportNumber": null,
      "birthCertificateSeria": null,
      "birthCertificateNumber": null,
      "companyName": null,
      "workAdress": null,
      "position": null,
      "regionResidenceId": "",
      "districtResidenceId": "",
      "placeOfResidence": null,
      "file": null,
      "staffId": 2257,
      "structureName": null,
      "currentpositionId": null,
      "profileId": null,
      "argosId": null,
      "tin": null,
      "regionEducationId": "",
      "districtEducationId": "",
      "educationalInstitution": null,
      "address": "Қорақалпоғистон Республикаси,  Тахиатош тумани",
      "pensionDateBegin": null,
      "pensionType": null,
      "status": "Мактаб/Лицей/Коллеж ўқувчиси",
      "dateOfDeath": null,
      "isChild": null,
      "relativeWorkType": null,
      "citizenType": null,
      "isSameOrganization": 0,
      "underAgeType": null,
      "ordered": 3,
      "relationId": 3,
      "birthOfDate": "2009-01-14T00:00:00",
      "yearOfDeath": 0,
      "districtBirthId": null
    }
  ];
  // item!: RelativeDTO;
  // products: any = [
  //   {
  //     id: '1000',
  //     code: 'f230fh0g3',
  //     name: 'Bamboo Watch',
  //     description: 'Product Description',
  //     image: 'bamboo-watch.jpg',
  //     price: 25,
  //     category: 'Accessories',
  //     quantity: 24,
  //     inventoryStatus: 'INSTOCK',
  //     rating: 5
  //   },
  // ];

  onSelectRow(event: any) {
    this.hideTable = false;
    this.selectedRowData = event.data;
    console.log(event.data, 'event Select data')
  }

  onloadLazy(event: TableLazyLoadEvent) {
    console.log(event, 'table event')
  }
}
